name: checking the AWS app

on: [push]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node: [ 14, 16, 18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build and test
        run: npm run
